name: Update Submodule

on:
  repository_dispatch:
    types: [content-update]

jobs:
  update-submodule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
      
      - name: Update submodule
        run: |
          git config --global url."https://${{ secrets.PAT_TOKEN }}@github.com/".insteadOf "https://github.com/"
          git submodule init
          git submodule update
          cd content
          OLD_HASH=$(git rev-parse HEAD)
          git pull origin main
          NEW_HASH=$(git rev-parse HEAD)
          LAST_COMMIT_MSG=$(git log -1 --pretty=%B)
          REPO_URL=$(git config --get remote.origin.url | sed 's/\.git$//' | sed 's/^https:\/\/github.com\///')
          DIFF_URL="https://github.com/${REPO_URL}/compare/${OLD_HASH}...${NEW_HASH}"
          cd ..
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add content
          git commit -m "${LAST_COMMIT_MSG}

          Submodule updated from ${OLD_HASH} to ${NEW_HASH}
          View changes: ${DIFF_URL}"
          git push
