name: Update Submodule

on:
  repository_dispatch:
    types: [content-update]

jobs:
  update-submodule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
      
      - name: Update submodule
        run: |
          git config --global url."https://${{ secrets.PAT_TOKEN }}@github.com/".insteadOf "https://github.com/"
          git submodule init
          git submodule update
          cd content
          git pull origin main
          cd ..
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add content
          git commit -m "Update Obsidian submodule"
          git push
